<span style="font-size: 5pt;">
<table>
  <tr>
    <th>Feature</th>
    <th>Type</th>
    <th>Variable</th>
    <th>Data Type/Description</th>
  </tr>
  <tr>
    <td>Age</td>
    <td>Objective Feature</td>
    <td>age</td>
    <td>int (days)</td>
  </tr>
  <tr>
    <td>Height</td>
    <td>Objective Feature</td>
    <td>height</td>
    <td>int (cm)</td>
  </tr>
  <tr>
    <td>Weight</td>
    <td>Objective Feature</td>
    <td>weight</td>
    <td>float (kg)</td>
  </tr>
  <tr>
    <td>Gender</td>
    <td>Objective Feature</td>
    <td>gender</td>
    <td>categorical code</td>
  </tr>
  <tr>
    <td>Systolic blood pressure</td>
    <td>Examination Feature</td>
    <td>ap_hi</td>
    <td>int</td>
  </tr>
  <tr>
    <td>Diastolic blood pressure</td>
    <td>Examination Feature</td>
    <td>ap_lo</td>
    <td>int</td>
  </tr>
  <tr>
    <td>Cholesterol</td>
    <td>Examination Feature</td>
    <td>cholesterol</td>
    <td>1: normal, 2: above normal, 3: well above normal</td>
  </tr>
  <tr>
    <td>Glucose</td>
    <td>Examination Feature</td>
    <td>gluc</td>
    <td>1: normal, 2: above normal, 3: well above normal</td>
  </tr>
  <tr>
    <td>Smoking</td>
    <td>Subjective Feature</td>
    <td>smoke</td>
    <td>binary</td>
  </tr>
  <tr>
    <td>Alcohol intake</td>
    <td>Subjective Feature</td>
    <td>alco</td>
    <td>binary</td>
  </tr>
  <tr>
    <td>Physical activity</td>
    <td>Subjective Feature</td>
    <td>active</td>
    <td>binary</td>
  </tr>
  <tr>
    <td>Presence or absence of cardiovascular disease</td>
    <td>Target Variable</td>
    <td>cardio</td>
    <td>binary</td>
  </tr>
</table>
</span>

In [154]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import xgboost as xgb
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, classification_report
from sklearn.model_selection import cross_val_score

In [110]:
df = pd.read_csv('cardio_train.csv',sep=';')

In [111]:
df=df.drop('id',axis=1)

In [112]:
df

age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
0      18393       2     168    62.0    110     80            1     1      0   
1      20228       1     156    85.0    140     90            3     1      0   
2      18857       1     165    64.0    130     70            3     1      0   
3      17623       2     169    82.0    150    100            1     1      0   
4      17474       1     156    56.0    100     60            1     1      0   
...      ...     ...     ...     ...    ...    ...          ...   ...    ...   
69995  19240       2     168    76.0    120     80            1     1      1   
69996  22601       1     158   126.0    140     90            2     2      0   
69997  19066       2     183   105.0    180     90            3     1      0   
69998  22431       1     163    72.0    135     80            1     2      0   
69999  20540       1     170    72.0    120     80            2     1      0   

       alco  active  cardio  
0         0       1       0  
1         0       1       1  
2         0       0       1  
3         0       1       1  
4         0       0       0  
...     ...     ...     ...  
69995     0       1       0  
69996     0       1       1  
69997     1       0       1  
69998     0       0       1  
69999     0       1       0  

[70000 rows x 12 columns]

In [136]:
df[['active']].value_counts()

active
1         56261
0         13739
Name: count, dtype: int64

In [114]:
x=df.drop('cardio',axis=1)

In [115]:
y=df[['cardio']]

In [116]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2, random_state=2)

In [117]:
xtrain

age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
59452  20611       1     167    74.0    150     80            1     1      0   
65441  14473       1     158    89.0    190   1000            1     1      0   
51371  21222       1     168   127.0    150     90            3     3      0   
21761  19926       1     160    70.0    130     80            1     1      0   
20337  14511       1     166    92.0    120     80            1     1      0   
...      ...     ...     ...     ...    ...    ...          ...   ...    ...   
53922  17743       1     160    61.0    120     80            1     1      0   
44295  23356       1     162    84.0    150     90            2     1      0   
33867  23383       1     167    92.0    140     90            1     1      0   
31019  19739       1     162    62.0    120     80            1     1      0   
44566  18156       1     165    89.0    120     80            1     1      0   

       alco  active  
59452     0       0  
65441     0       0  
51371     0       1  
21761     0       1  
20337     0       1  
...     ...     ...  
53922     0       0  
44295     0       1  
33867     0       0  
31019     0       0  
44566     0       1  

[56000 rows x 11 columns]

In [118]:
ytest

cardio
7142        0
27818       0
43572       0
52877       0
39845       1
...       ...
6855        1
18877       1
25962       1
35167       0
43554       1

[14000 rows x 1 columns]

**<font size="20">DecisionTreeClassifier</font>**

In [68]:
from sklearn.tree import DecisionTreeClassifier
dect = DecisionTreeClassifier()
dect.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [73]:
dect.score(xtest,ytest)

0.6351428571428571

In [140]:
result = cross_val_score(DecisionTreeClassifier(), x, y, cv=10) 
result.mean()

0.6336714285714284

In [147]:
df.head()

age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
0  18393       2     168    62.0    110     80            1     1      0   
1  20228       1     156    85.0    140     90            3     1      0   
2  18857       1     165    64.0    130     70            3     1      0   
3  17623       2     169    82.0    150    100            1     1      0   
4  17474       1     156    56.0    100     60            1     1      0   

   alco  active  cardio  
0     0       1       0  
1     0       1       1  
2     0       0       1  
3     0       1       1  
4     0       0       0

In [148]:
dect.predict([[8906,1,172.2,90,130,89,2,1,0,0,1]])

C:\Users\Msi Laptop\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [86]:
cm = confusion_matrix(ytest, ypred)
cm

array([[4466, 2563],
       [2545, 4426]], dtype=int64)

In [87]:
tn, fp, fn, tp = cm.ravel()

In [88]:
print(f"True Positives (TP): {tp}")
print(f"False Positives (FP): {fp}")
print(f"False Negatives (FN): {fn}")
print(f"True Negatives (TN): {tn}")

True Positives (TP): 4426
False Positives (FP): 2563
False Negatives (FN): 2545
True Negatives (TN): 4466


In [82]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [120]:
 accuracy_score(ytest, ypred)

0.6351428571428571

**<font size="50">Random Forest</font>**

In [121]:
from sklearn.ensemble import RandomForestClassifier

In [122]:
ranclas=RandomForestClassifier(n_estimators=155)

In [123]:
ranclas

RandomForestClassifier(n_estimators=155)

In [124]:
ranclas.fit(xtrain,ytrain)

C:\Users\Msi Laptop\anaconda3\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier(n_estimators=155)

In [125]:
clf_pred=ranclas.predict(xtest)

In [126]:
accuracy_score(clf_pred, ypred)

0.7508571428571429

In [149]:
ranclas.predict([[8906,1,172.2,90,130,89,2,1,0,0,1]])

C:\Users\Msi Laptop\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

**<font size="50">SVM</font>**

In [101]:
from sklearn.svm import SVC

In [43]:
svm_model = SVC(kernel='linear',C=20,gamma='auto')
svm_model.fit(xtrain,ytrain)

C:\Users\Msi Laptop\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=20, gamma='auto', kernel='linear')

In [44]:
svm_model.score(xtest, ytest)

0.7232142857142857

In [103]:
svm_model.predict([[8906,1,172.2,90,130,89,2,1,0,0,1]])

C:\Users\Msi Laptop\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

**<font size="50">KNN</font>**

In [48]:
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier(n_neighbors=3)

In [50]:
KNN.fit(xtrain,ytrain)

C:\Users\Msi Laptop\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=3)

In [51]:
KNN.score(xtest,ytest)

0.6665

In [104]:
KNN.predict([[8906,1,172.2,90,130,89,2,1,0,0,1]])

C:\Users\Msi Laptop\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

**<font size="50">Xg Boost</font>**

In [131]:
clf = xgb.XGBClassifier(use_label_encoder=False, eval_metric='logloss')
clf.fit(xtrain, ytrain)

C:\Users\Msi Laptop\anaconda3\Lib\site-packages\xgboost\core.py:158: UserWarning: [12:58:40] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0c55ff5f71b100e98-1\xgboost\xgboost-ci-windows\src\learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, random_state=None, ...)

In [132]:
clf.score(xtest,ytest)

0.7335714285714285

In [133]:
clf.predict([[8906,1,172.2,90,130,89,2,1,0,0,1]])

array([0])

**<font size="50">Logistic Regression</font>**

In [55]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(xtrain, ytrain)

C:\Users\Msi Laptop\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Msi Laptop\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [56]:
model.score(xtest,ytest)

0.6947142857142857

In [107]:
model.predict([[8906,1,172.2,90,130,89,2,1,0,0,1]])

C:\Users\Msi Laptop\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0], dtype=int64)